"""
Small-scale replication of the recursive-training setup in Shumailov et al.
("AI models collapse when trained on recursively generated data", Nature, 2024),
using GPT-2 small (124M) instead of OPT-125m, and Wikipedia featured articles
scraped with Apify Website Content Crawler instead of wikitext-2.

Each generation fine-tunes a fresh copy of pretrained GPT-2 on the data produced by
the previous generation, following the paper's recipe: split training text into
64-token blocks, prompt the model with every block, keep the next 64 tokens it writes.

Regimes (training data of generation n >= 1):
  replace  : 100% text generated by generation n-1
  orig10   : 90% generated + 10% real blocks resampled from the original gen-0 pool
  fresh10  : 90% generated + 10% real blocks that no earlier generation used, from articles
             outside the gen-0 pool and the test set (one article can supply blocks to
             several generations, but no block is used twice)
  fresh50  : 50% generated + 50% real blocks, drawn the same way as fresh10

Metrics per generation:
  test_ppl     perplexity on held-out real articles (lower is better)
  gen metrics  diversity and tail coverage of the text the model writes
"""
import argparse, json, math, random, re, time, pathlib
from collections import Counter

import torch
import torch.nn.functional as F
from transformers import AutoModelForCausalLM, AutoTokenizer

BLOCK = 64
EOS = 50256
CUT = re.compile(
    r"^#{1,6}\s*(References|Notes|See also|External links|Further reading|Sources|Citations|"
    r"Bibliography|Footnotes|Works cited|Notes and references|Explanatory notes|Primary sources|"
    r"Secondary sources|Cited sources|General and cited sources|Literature cited)\b",
    re.I | re.M,
)
WORD = re.compile(r"[A-Za-z][A-Za-z'\-]*")


def clean_markdown(md: str) -> str:
    m = CUT.search(md)
    if m:
        md = md[: m.start()]
    md = re.sub(r"!\[[^\]]*\]\((?:[^()]|\([^)]*\))*\)", "", md)             # images
    md = re.sub(r"\[([^\]]*)\]\((?:[^()]|\([^)]*\))*\)", r"\1", md)          # links -> anchor text
    md = re.sub(r"^#{1,6}\s*", "", md, flags=re.M)                           # heading markers
    md = re.sub(r"\\([\-()_*\[\].#!])", r"\1", md)                           # markdown escapes
    for _ in range(2):
        md = re.sub(r"(\*{1,3}|_{1,3})([^*_\n]+?)\1", r"\2", md)             # emphasis (nested)
    md = re.sub(r"\[\d+\]|\[citation needed\]|\[[a-z]\]", "", md)            # citation leftovers
    lines = [l.strip() for l in md.split("\n")]
    lines = [l for l in lines if len(l) > 60 and not l.startswith(("|", "-", "*", ">"))]
    return "\n".join(lines)


def words(text):
    return [w.lower() for w in WORD.findall(text)]


def lr_lambda(total, warm):
    def f(step):
        if step < warm:
            return (step + 1) / warm
        return max(0.0, (total - step) / max(1, total - warm))
    return f


def train(blocks, epochs, dev, lr, bs, seed):
    torch.manual_seed(seed)
    random.seed(seed)
    model = AutoModelForCausalLM.from_pretrained("gpt2").to(dev)
    model.train()
    opt = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=0.0)
    data = torch.tensor(blocks, dtype=torch.long)
    n = len(data)
    total = epochs * math.ceil(n / bs)
    sched = torch.optim.lr_scheduler.LambdaLR(opt, lr_lambda(total, max(1, total // 20)))
    for _ in range(epochs):
        perm = torch.randperm(n)
        for i in range(0, n, bs):
            x = data[perm[i : i + bs]].to(dev)
            loss = model(input_ids=x, labels=x).loss
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step()
            sched.step()
            opt.zero_grad(set_to_none=True)
    model.eval()
    del opt, sched, data
    free(dev)
    return model


def free(dev):
    if dev == "mps":
        torch.mps.empty_cache()


@torch.no_grad()
def block_nll(model, blocks, dev, bs=16):
    """Mean token NLL per block (list), used for perplexity and its distribution."""
    out = []
    for i in range(0, len(blocks), bs):
        x = torch.tensor(blocks[i : i + bs], dtype=torch.long, device=dev)
        logits = model(input_ids=x).logits[:, :-1].float()
        tgt = x[:, 1:]
        nll = F.cross_entropy(logits.reshape(-1, logits.size(-1)), tgt.reshape(-1), reduction="none")
        out += nll.view(tgt.shape).mean(dim=1).tolist()
        del logits, nll
    free(dev)
    return out


@torch.no_grad()
def generate(model, prompts, dev, decode, bs, top_p, seed):
    torch.manual_seed(seed)
    outs = []
    for i in range(0, len(prompts), bs):
        x = torch.tensor(prompts[i : i + bs], dtype=torch.long, device=dev)
        kw = dict(attention_mask=torch.ones_like(x), max_new_tokens=BLOCK, min_new_tokens=BLOCK, pad_token_id=EOS)
        if decode == "beam":
            g = model.generate(x, num_beams=5, do_sample=False, **kw)
        else:
            g = model.generate(x, do_sample=True, top_p=top_p, top_k=0, temperature=1.0, **kw)
        outs += g[:, x.size(1) : x.size(1) + BLOCK].tolist()
        del g
    free(dev)
    return outs


def text_metrics(tok, gen_blocks, rare_words):
    texts = [tok.decode(b) for b in gen_blocks]
    ws_all, bigrams, rep4 = [], [], 0
    for t in texts:
        ws = words(t)
        ws_all += ws
        bigrams += list(zip(ws, ws[1:]))
        grams = list(zip(ws, ws[1:], ws[2:], ws[3:]))
        if len(grams) != len(set(grams)):
            rep4 += 1
    vocab = set(ws_all)
    return {
        "gen_words": len(ws_all),
        "gen_vocab": len(vocab),
        "distinct1": round(len(vocab) / max(1, len(ws_all)), 4),
        "distinct2": round(len(set(bigrams)) / max(1, len(bigrams)), 4),
        "rep4_share": round(rep4 / max(1, len(texts)), 4),
        "rare_words_kept": round(len(vocab & rare_words) / max(1, len(rare_words)), 4),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--items", default="wcc_wiki_items.json")
    ap.add_argument("--out", default="results")
    ap.add_argument("--train_tokens", type=int, default=120_000)
    ap.add_argument("--test_tokens", type=int, default=40_000)
    ap.add_argument("--gens", type=int, default=5)
    ap.add_argument("--epochs", type=int, default=3)
    ap.add_argument("--lr", type=float, default=5e-5)
    ap.add_argument("--bs", type=int, default=32)
    ap.add_argument("--gen_bs", type=int, default=64)
    ap.add_argument("--decode", default="sample", choices=["sample", "beam"])
    ap.add_argument("--top_p", type=float, default=0.9)
    ap.add_argument("--regimes", default="replace,orig10,fresh10,fresh50")
    ap.add_argument("--per_doc", type=int, default=10)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--device", default="mps")
    a = ap.parse_args()

    out = pathlib.Path(a.out)
    out.mkdir(exist_ok=True)
    log = open(out / "log.txt", "a")

    def say(*s):
        msg = " ".join(str(x) for x in s)
        print(msg, flush=True)
        log.write(msg + "\n")
        log.flush()

    tok = AutoTokenizer.from_pretrained("gpt2")
    items = json.load(open(a.items))
    docs = []
    for it in items:
        text = clean_markdown(it.get("markdown") or "")
        if len(text) > 2000:
            docs.append({"url": it["url"], "text": text})
    rnd = random.Random(a.seed)
    rnd.shuffle(docs)

    def to_blocks(text):
        ids = tok(text + "\n\n")["input_ids"]
        return [ids[i : i + BLOCK] for i in range(0, len(ids) - BLOCK + 1, BLOCK)]

    # Split by article so test, gen-0 pool, and fresh pool never share an article.
    # Test and gen-0 pool take up to `per_doc` blocks from many articles, for broad topic coverage.
    n_train = a.train_tokens // BLOCK
    n_test = a.test_tokens // BLOCK
    test, pool0, fresh, used = [], [], [], {"test": [], "pool0": [], "fresh": []}
    for d in docs:
        b = to_blocks(d["text"])
        if len(test) < n_test:
            test += b[: a.per_doc]; used["test"].append(d["url"])
        elif len(pool0) < n_train:
            pool0 += b[: a.per_doc]; used["pool0"].append(d["url"])
        else:
            fresh += b; used["fresh"].append(d["url"])
    test, pool0 = test[:n_test], pool0[:n_train]
    random.Random(a.seed + 7).shuffle(fresh)  # fresh data = a random sample of new articles
    json.dump(used, open(out / "split_urls.json", "w"), indent=1)
    say(f"docs={len(docs)} test_blocks={len(test)} pool0_blocks={len(pool0)} fresh_blocks={len(fresh)} "
        f"n_train={n_train} decode={a.decode} top_p={a.top_p} epochs={a.epochs}")

    counts = Counter(words(tok.decode([t for b in pool0 for t in b])))
    rare = {w for w, c in counts.items() if c <= 2}
    say(f"pool0 word types={len(counts)} rare types (freq<=2)={len(rare)}")

    # Fixed probe prompts from the test set, for side-by-side samples across generations.
    probe = [test[i] for i in (0, len(test) // 2, len(test) - 1)]

    results = []
    res_path = out / "results.json"

    def record(regime, gen, model, train_blocks, gen_blocks, secs, model0=None):
        test_nll = block_nll(model, test, a.device)
        row = {"regime": regime, "gen": gen, "test_ppl": round(math.exp(sum(test_nll) / len(test_nll)), 3),
               "train_blocks": len(train_blocks), "secs": round(secs, 1)}
        row.update(text_metrics(tok, gen_blocks, rare))
        if model0 is not None:
            g_nll = block_nll(model0, gen_blocks, a.device)
            row["gen_ppl_under_gen0"] = round(math.exp(sum(g_nll) / len(g_nll)), 3)
            g_sorted = sorted(math.exp(v) for v in g_nll)
            row["gen_ppl_p10_p50_p90"] = [round(g_sorted[int(q * (len(g_sorted) - 1))], 2) for q in (0.1, 0.5, 0.9)]
        samples = generate(model, probe, a.device, a.decode, len(probe), a.top_p, a.seed)
        row["probe_samples"] = [tok.decode(s) for s in samples]
        results.append(row)
        json.dump(results, open(res_path, "w"), indent=1)
        say(json.dumps({k: v for k, v in row.items() if k != "probe_samples"}))

    # Generation 0: real data only, shared by all regimes.
    t0 = time.time()
    model0 = train(pool0, a.epochs, a.device, a.lr, a.bs, a.seed)
    say(f"  gen0 trained in {time.time() - t0:.0f}s")
    synth0 = generate(model0, pool0, a.device, a.decode, a.gen_bs, a.top_p, a.seed)
    say(f"  gen0 generated at {time.time() - t0:.0f}s")
    record("all", 0, model0, pool0, synth0, time.time() - t0, model0)
    base = AutoModelForCausalLM.from_pretrained("gpt2").to(a.device).eval()
    base_nll = block_nll(base, test, a.device)
    say(json.dumps({"regime": "pretrained_gpt2_no_finetune", "test_ppl": round(math.exp(sum(base_nll) / len(base_nll)), 3)}))
    del base

    for regime in a.regimes.split(","):
        prev = synth0
        fresh_ptr = 0
        rr = random.Random(a.seed + 1)
        for gen in range(1, a.gens + 1):
            t0 = time.time()
            if regime == "replace":
                train_blocks = list(prev)
            else:
                real_share = 0.5 if regime.endswith("50") else 0.1
                n_real = int(n_train * real_share)
                keep = rr.sample(prev, n_train - n_real)
                if regime.startswith("orig"):
                    real = rr.sample(pool0, n_real)
                else:
                    real = fresh[fresh_ptr : fresh_ptr + n_real]
                    fresh_ptr += n_real
                    assert len(real) == n_real, "ran out of fresh blocks"
                train_blocks = keep + real
                rr.shuffle(train_blocks)
            model = train(train_blocks, a.epochs, a.device, a.lr, a.bs, a.seed + gen)
            say(f"  {regime} gen{gen} trained in {time.time() - t0:.0f}s")
            synth = generate(model, train_blocks, a.device, a.decode, a.gen_bs, a.top_p, a.seed + gen)
            record(regime, gen, model, train_blocks, synth, time.time() - t0, model0)
            prev = synth
            del model
            if a.device == "mps":
                torch.mps.empty_cache()
    say("DONE")


if __name__ == "__main__":
    main()
